environment: ${SPRING_PROFILES_ACTIVE:local}

server:
  port : 8088

spring:
  application:
    name: cnap-examples-spring-boot-rest-kafka-json-service
  kafka:
    replicas: 1
    partitions: 1
    bootstrap:
     servers: "localhost:9092"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
